language: java
dist: bionic
jdk:
  - "openjdk11"
  - "openjdk8"
cache:
  directories:
    - "/home/travis/.m2"
install: "/bin/true"
script:
  - (cd ./docker; docker-compose down -v; docker-compose up -d)
  - ./mvnw clean package -DenableStandaloneTests=true -DenableOomTests=true -DenableFuzzyStartTests=true
  - rm -rf ~/.m2/repository/name/nkonev/r2dbc-migrate
